/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ultrawise.softwareproduct.idevplatform;

public final class R {
    public static final class anim {
        public static int fiand_in=0x7f040000;
        public static int fiand_out=0x7f040001;
        public static int slide_in_from_bottom=0x7f040002;
        public static int slide_in_from_top=0x7f040003;
        public static int slide_out_to_bottom=0x7f040004;
        public static int slide_out_to_top=0x7f040005;
    }
    public static final class attr {
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int LeftLine=0x7f010011;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int activeColor=0x7f01000d;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int activeRadius=0x7f010015;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>stroke</code></td><td>0</td><td></td></tr>
<tr><td><code>fill</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int activeType=0x7f010013;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int barColor=0x7f010003;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int barLength=0x7f01000b;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int barWidth=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int centered=0x7f01000f;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int circleColor=0x7f010008;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int circleSeparation=0x7f010014;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int click_remove_id=0x7f010026;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int collapsed_height=0x7f010016;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int delayMillis=0x7f010007;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drag_enabled=0x7f010020;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drag_handle_id=0x7f010024;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drag_scroll_start=0x7f010017;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>onDown</code></td><td>0</td><td></td></tr>
<tr><td><code>onMove</code></td><td>1</td><td></td></tr>
<tr><td><code>onLongPress</code></td><td>2</td><td></td></tr>
</table>
         */
        public static int drag_start_mode=0x7f010023;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int drop_animation_duration=0x7f01001f;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fadeOut=0x7f010010;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int fling_handle_id=0x7f010025;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int float_alpha=0x7f01001c;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int float_background_color=0x7f010019;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int inactiveColor=0x7f01000e;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>stroke</code></td><td>0</td><td></td></tr>
<tr><td><code>fill</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int inactiveType=0x7f010012;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int max_drag_scroll_speed=0x7f010018;
        /**  BELOW HERE ARE DEPRECEATED. DO NOT USE. 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int ptrAdapterViewBackground=0x7f010038;
        /**  Style of Animation should be used displayed when pulling. 
         <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>rotate</code></td><td>0x0</td><td></td></tr>
<tr><td><code>flip</code></td><td>0x1</td><td></td></tr>
</table>
         */
        public static int ptrAnimationStyle=0x7f010034;
        /**  Drawable to use as Loading Indicator. Changes both Header and Footer. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrDrawable=0x7f01002e;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrDrawableBottom=0x7f01003a;
        /**  Drawable to use as Loading Indicator in the Footer View. Overrides value set in ptrDrawable. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrDrawableEnd=0x7f010030;
        /**  Drawable to use as Loading Indicator in the Header View. Overrides value set in ptrDrawable. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrDrawableStart=0x7f01002f;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrDrawableTop=0x7f010039;
        /**  A drawable to use as the background of the Header and Footer Loading Views 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int ptrHeaderBackground=0x7f010029;
        /**  Text Color of the Header and Footer Loading Views Sub Header 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int ptrHeaderSubTextColor=0x7f01002b;
        /**  Base text color, typeface, size, and style for Header and Footer Loading Views 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrHeaderTextAppearance=0x7f010032;
        /**  Text Color of the Header and Footer Loading Views 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int ptrHeaderTextColor=0x7f01002a;
        /** 
        	Whether PullToRefreshListView has it's extras enabled. This allows the user to be 
        	able to scroll while refreshing, and behaves better. It acheives this by adding
        	Header and/or Footer Views to the ListView.
        
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
         */
        public static int ptrListViewExtrasEnabled=0x7f010036;
        /**  Mode of Pull-to-Refresh that should be used 
         <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>disabled</code></td><td>0x0</td><td></td></tr>
<tr><td><code>pullFromStart</code></td><td>0x1</td><td></td></tr>
<tr><td><code>pullFromEnd</code></td><td>0x2</td><td></td></tr>
<tr><td><code>both</code></td><td>0x3</td><td></td></tr>
<tr><td><code>manualOnly</code></td><td>0x4</td><td></td></tr>
<tr><td><code>pullDownFromTop</code></td><td>0x1</td><td> These last two are depreacted </td></tr>
<tr><td><code>pullUpFromBottom</code></td><td>0x2</td><td></td></tr>
</table>
         */
        public static int ptrMode=0x7f01002c;
        /**  Whether Android's built-in Over Scroll should be utilised for Pull-to-Refresh. 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
         */
        public static int ptrOverScroll=0x7f010031;
        /**  A drawable to use as the background of the Refreshable View 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static int ptrRefreshableViewBackground=0x7f010028;
        /** 
        	Whether the Drawable should be continually rotated as you pull. This only
        	takes effect when using the 'Rotate' Animation Style.
        
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
         */
        public static int ptrRotateDrawableWhilePulling=0x7f010037;
        /**  Whether the user can scroll while the View is Refreshing 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
         */
        public static int ptrScrollingWhileRefreshingEnabled=0x7f010035;
        /**  Whether the Indicator overlay(s) should be used 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
         */
        public static int ptrShowIndicator=0x7f01002d;
        /**  Base text color, typeface, size, and style for Header and Footer Loading Views Sub Header 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int ptrSubHeaderTextAppearance=0x7f010033;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int radius=0x7f010009;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int remove_animation_duration=0x7f01001e;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int remove_enabled=0x7f010022;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>clickRemove</code></td><td>0</td><td></td></tr>
<tr><td><code>flingRemove</code></td><td>1</td><td></td></tr>
</table>
         */
        public static int remove_mode=0x7f01001a;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int rimColor=0x7f010004;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int rimWidth=0x7f010005;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int sidebuffer=0x7f01000c;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int slide_shuffle_speed=0x7f01001d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int sort_enabled=0x7f010021;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int spinSpeed=0x7f010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int text=0x7f010000;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int textColor=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int textSize=0x7f010002;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int track_drag_sort=0x7f01001b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int use_default_controller=0x7f010027;
    }
    public static final class color {
        public static int circle_color=0x7f060003;
        public static int header_bg_common=0x7f060001;
        public static int ring_color=0x7f060004;
        public static int title_txt_color=0x7f060002;
        public static int white=0x7f060000;
    }
    public static final class dimen {
        /** 
         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw600dp devices (e.g. 7" tablets) here.
    

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static int activity_horizontal_margin=0x7f070006;
        public static int activity_login=0x7f070008;
        public static int activity_vertical_margin=0x7f070007;
        public static int header_footer_left_right_padding=0x7f070003;
        public static int header_footer_top_bottom_padding=0x7f070004;
        public static int indicator_corner_radius=0x7f070001;
        public static int indicator_internal_padding=0x7f070002;
        /**  Default screen margins, per the Android Design guidelines. 
 pull to refresh 
         */
        public static int indicator_right_padding=0x7f070000;
        public static int menu_shadow_width=0x7f070005;
    }
    public static final class drawable {
        public static int default_ptr_flip=0x7f020000;
        public static int default_ptr_rotate=0x7f020001;
        public static int fille_box=0x7f020002;
        public static int img_default=0x7f020003;
        public static int indicator_arrow=0x7f020004;
        public static int indicator_bg_bottom=0x7f020005;
        public static int indicator_bg_top=0x7f020006;
    }
    public static final class id {
        public static int both=0x7f05000a;
        public static int clickRemove=0x7f050002;
        public static int dialog_msg=0x7f050011;
        public static int disabled=0x7f050007;
        public static int fill=0x7f050001;
        public static int fl_inner=0x7f050013;
        public static int flingRemove=0x7f050003;
        public static int flip=0x7f05000f;
        public static int manualOnly=0x7f05000b;
        public static int onDown=0x7f050004;
        public static int onLongPress=0x7f050006;
        public static int onMove=0x7f050005;
        public static int progressBar=0x7f050010;
        public static int progressBarTwo=0x7f050012;
        public static int pullDownFromTop=0x7f05000c;
        public static int pullFromEnd=0x7f050009;
        public static int pullFromStart=0x7f050008;
        public static int pullUpFromBottom=0x7f05000d;
        public static int pull_to_refresh_image=0x7f050014;
        public static int pull_to_refresh_progress=0x7f050015;
        public static int pull_to_refresh_sub_text=0x7f050017;
        public static int pull_to_refresh_text=0x7f050016;
        public static int rotate=0x7f05000e;
        public static int stroke=0x7f050000;
    }
    public static final class layout {
        public static int dialog_layout=0x7f030000;
        public static int dialog_layout_call=0x7f030001;
        public static int pull_to_refresh_header_horizontal=0x7f030002;
        public static int pull_to_refresh_header_vertical=0x7f030003;
    }
    public static final class string {
        public static int app_name=0x7f080000;
        /**  Just use standard Pull Down String when pulling up. These can be set for languages which require it 
         */
        public static int pull_to_refresh_from_bottom_pull_label=0x7f080004;
        public static int pull_to_refresh_from_bottom_refreshing_label=0x7f080006;
        public static int pull_to_refresh_from_bottom_release_label=0x7f080005;
        public static int pull_to_refresh_pull_label=0x7f080001;
        public static int pull_to_refresh_refreshing_label=0x7f080003;
        public static int pull_to_refresh_release_label=0x7f080002;
    }
    public static final class style {
        /** 
        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static int AppBaseTheme=0x7f090003;
        public static int dialog_animation=0x7f090001;
        /**  背景缓存颜色 
         */
        public static int dialog_translucent=0x7f090000;
        public static int popupDialog=0x7f090002;
    }
    public static final class styleable {
        /** Attributes that can be used with a CircleFlowIndicator.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CircleFlowIndicator_LeftLine com.ultrawise.softwareproduct.idevplatform:LeftLine}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_activeColor com.ultrawise.softwareproduct.idevplatform:activeColor}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_activeRadius com.ultrawise.softwareproduct.idevplatform:activeRadius}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_activeType com.ultrawise.softwareproduct.idevplatform:activeType}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_centered com.ultrawise.softwareproduct.idevplatform:centered}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_circleSeparation com.ultrawise.softwareproduct.idevplatform:circleSeparation}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_fadeOut com.ultrawise.softwareproduct.idevplatform:fadeOut}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_inactiveColor com.ultrawise.softwareproduct.idevplatform:inactiveColor}</code></td><td></td></tr>
           <tr><td><code>{@link #CircleFlowIndicator_inactiveType com.ultrawise.softwareproduct.idevplatform:inactiveType}</code></td><td></td></tr>
           </table>
           @see #CircleFlowIndicator_LeftLine
           @see #CircleFlowIndicator_activeColor
           @see #CircleFlowIndicator_activeRadius
           @see #CircleFlowIndicator_activeType
           @see #CircleFlowIndicator_centered
           @see #CircleFlowIndicator_circleSeparation
           @see #CircleFlowIndicator_fadeOut
           @see #CircleFlowIndicator_inactiveColor
           @see #CircleFlowIndicator_inactiveType
         */
        public static final int[] CircleFlowIndicator = {
            0x7f01000d, 0x7f01000e, 0x7f01000f, 0x7f010010,
            0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014,
            0x7f010015
        };
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#LeftLine}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:LeftLine
        */
        public static final int CircleFlowIndicator_LeftLine = 4;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#activeColor}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:activeColor
        */
        public static final int CircleFlowIndicator_activeColor = 0;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#activeRadius}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:activeRadius
        */
        public static final int CircleFlowIndicator_activeRadius = 8;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#activeType}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>stroke</code></td><td>0</td><td></td></tr>
<tr><td><code>fill</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.ultrawise.softwareproduct.idevplatform:activeType
        */
        public static final int CircleFlowIndicator_activeType = 6;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#centered}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:centered
        */
        public static final int CircleFlowIndicator_centered = 2;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#circleSeparation}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:circleSeparation
        */
        public static final int CircleFlowIndicator_circleSeparation = 7;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#fadeOut}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:fadeOut
        */
        public static final int CircleFlowIndicator_fadeOut = 3;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#inactiveColor}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:inactiveColor
        */
        public static final int CircleFlowIndicator_inactiveColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#inactiveType}
          attribute's value can be found in the {@link #CircleFlowIndicator} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>stroke</code></td><td>0</td><td></td></tr>
<tr><td><code>fill</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.ultrawise.softwareproduct.idevplatform:inactiveType
        */
        public static final int CircleFlowIndicator_inactiveType = 5;
        /**  DragSortListView 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #DragSortListView_click_remove_id com.ultrawise.softwareproduct.idevplatform:click_remove_id}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_collapsed_height com.ultrawise.softwareproduct.idevplatform:collapsed_height}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_enabled com.ultrawise.softwareproduct.idevplatform:drag_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_handle_id com.ultrawise.softwareproduct.idevplatform:drag_handle_id}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_scroll_start com.ultrawise.softwareproduct.idevplatform:drag_scroll_start}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drag_start_mode com.ultrawise.softwareproduct.idevplatform:drag_start_mode}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_drop_animation_duration com.ultrawise.softwareproduct.idevplatform:drop_animation_duration}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_fling_handle_id com.ultrawise.softwareproduct.idevplatform:fling_handle_id}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_float_alpha com.ultrawise.softwareproduct.idevplatform:float_alpha}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_float_background_color com.ultrawise.softwareproduct.idevplatform:float_background_color}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_max_drag_scroll_speed com.ultrawise.softwareproduct.idevplatform:max_drag_scroll_speed}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_remove_animation_duration com.ultrawise.softwareproduct.idevplatform:remove_animation_duration}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_remove_enabled com.ultrawise.softwareproduct.idevplatform:remove_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_remove_mode com.ultrawise.softwareproduct.idevplatform:remove_mode}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_slide_shuffle_speed com.ultrawise.softwareproduct.idevplatform:slide_shuffle_speed}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_sort_enabled com.ultrawise.softwareproduct.idevplatform:sort_enabled}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_track_drag_sort com.ultrawise.softwareproduct.idevplatform:track_drag_sort}</code></td><td></td></tr>
           <tr><td><code>{@link #DragSortListView_use_default_controller com.ultrawise.softwareproduct.idevplatform:use_default_controller}</code></td><td></td></tr>
           </table>
           @see #DragSortListView_click_remove_id
           @see #DragSortListView_collapsed_height
           @see #DragSortListView_drag_enabled
           @see #DragSortListView_drag_handle_id
           @see #DragSortListView_drag_scroll_start
           @see #DragSortListView_drag_start_mode
           @see #DragSortListView_drop_animation_duration
           @see #DragSortListView_fling_handle_id
           @see #DragSortListView_float_alpha
           @see #DragSortListView_float_background_color
           @see #DragSortListView_max_drag_scroll_speed
           @see #DragSortListView_remove_animation_duration
           @see #DragSortListView_remove_enabled
           @see #DragSortListView_remove_mode
           @see #DragSortListView_slide_shuffle_speed
           @see #DragSortListView_sort_enabled
           @see #DragSortListView_track_drag_sort
           @see #DragSortListView_use_default_controller
         */
        public static final int[] DragSortListView = {
            0x7f010016, 0x7f010017, 0x7f010018, 0x7f010019,
            0x7f01001a, 0x7f01001b, 0x7f01001c, 0x7f01001d,
            0x7f01001e, 0x7f01001f, 0x7f010020, 0x7f010021,
            0x7f010022, 0x7f010023, 0x7f010024, 0x7f010025,
            0x7f010026, 0x7f010027
        };
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#click_remove_id}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:click_remove_id
        */
        public static final int DragSortListView_click_remove_id = 16;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#collapsed_height}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:collapsed_height
        */
        public static final int DragSortListView_collapsed_height = 0;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#drag_enabled}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:drag_enabled
        */
        public static final int DragSortListView_drag_enabled = 10;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#drag_handle_id}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:drag_handle_id
        */
        public static final int DragSortListView_drag_handle_id = 14;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#drag_scroll_start}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:drag_scroll_start
        */
        public static final int DragSortListView_drag_scroll_start = 1;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#drag_start_mode}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>onDown</code></td><td>0</td><td></td></tr>
<tr><td><code>onMove</code></td><td>1</td><td></td></tr>
<tr><td><code>onLongPress</code></td><td>2</td><td></td></tr>
</table>
          @attr name com.ultrawise.softwareproduct.idevplatform:drag_start_mode
        */
        public static final int DragSortListView_drag_start_mode = 13;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#drop_animation_duration}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:drop_animation_duration
        */
        public static final int DragSortListView_drop_animation_duration = 9;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#fling_handle_id}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:fling_handle_id
        */
        public static final int DragSortListView_fling_handle_id = 15;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#float_alpha}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:float_alpha
        */
        public static final int DragSortListView_float_alpha = 6;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#float_background_color}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:float_background_color
        */
        public static final int DragSortListView_float_background_color = 3;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#max_drag_scroll_speed}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:max_drag_scroll_speed
        */
        public static final int DragSortListView_max_drag_scroll_speed = 2;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#remove_animation_duration}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:remove_animation_duration
        */
        public static final int DragSortListView_remove_animation_duration = 8;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#remove_enabled}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:remove_enabled
        */
        public static final int DragSortListView_remove_enabled = 12;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#remove_mode}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>clickRemove</code></td><td>0</td><td></td></tr>
<tr><td><code>flingRemove</code></td><td>1</td><td></td></tr>
</table>
          @attr name com.ultrawise.softwareproduct.idevplatform:remove_mode
        */
        public static final int DragSortListView_remove_mode = 4;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#slide_shuffle_speed}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:slide_shuffle_speed
        */
        public static final int DragSortListView_slide_shuffle_speed = 7;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#sort_enabled}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:sort_enabled
        */
        public static final int DragSortListView_sort_enabled = 11;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#track_drag_sort}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:track_drag_sort
        */
        public static final int DragSortListView_track_drag_sort = 5;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#use_default_controller}
          attribute's value can be found in the {@link #DragSortListView} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:use_default_controller
        */
        public static final int DragSortListView_use_default_controller = 17;
        /** Attributes that can be used with a ProgressWheel.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ProgressWheel_barColor com.ultrawise.softwareproduct.idevplatform:barColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_barLength com.ultrawise.softwareproduct.idevplatform:barLength}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_barWidth com.ultrawise.softwareproduct.idevplatform:barWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_circleColor com.ultrawise.softwareproduct.idevplatform:circleColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_delayMillis com.ultrawise.softwareproduct.idevplatform:delayMillis}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_radius com.ultrawise.softwareproduct.idevplatform:radius}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_rimColor com.ultrawise.softwareproduct.idevplatform:rimColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_rimWidth com.ultrawise.softwareproduct.idevplatform:rimWidth}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_spinSpeed com.ultrawise.softwareproduct.idevplatform:spinSpeed}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_text com.ultrawise.softwareproduct.idevplatform:text}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_textColor com.ultrawise.softwareproduct.idevplatform:textColor}</code></td><td></td></tr>
           <tr><td><code>{@link #ProgressWheel_textSize com.ultrawise.softwareproduct.idevplatform:textSize}</code></td><td></td></tr>
           </table>
           @see #ProgressWheel_barColor
           @see #ProgressWheel_barLength
           @see #ProgressWheel_barWidth
           @see #ProgressWheel_circleColor
           @see #ProgressWheel_delayMillis
           @see #ProgressWheel_radius
           @see #ProgressWheel_rimColor
           @see #ProgressWheel_rimWidth
           @see #ProgressWheel_spinSpeed
           @see #ProgressWheel_text
           @see #ProgressWheel_textColor
           @see #ProgressWheel_textSize
         */
        public static final int[] ProgressWheel = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b
        };
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#barColor}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:barColor
        */
        public static final int ProgressWheel_barColor = 3;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#barLength}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:barLength
        */
        public static final int ProgressWheel_barLength = 11;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#barWidth}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:barWidth
        */
        public static final int ProgressWheel_barWidth = 10;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#circleColor}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:circleColor
        */
        public static final int ProgressWheel_circleColor = 8;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#delayMillis}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:delayMillis
        */
        public static final int ProgressWheel_delayMillis = 7;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#radius}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:radius
        */
        public static final int ProgressWheel_radius = 9;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#rimColor}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:rimColor
        */
        public static final int ProgressWheel_rimColor = 4;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#rimWidth}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:rimWidth
        */
        public static final int ProgressWheel_rimWidth = 5;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#spinSpeed}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:spinSpeed
        */
        public static final int ProgressWheel_spinSpeed = 6;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#text}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:text
        */
        public static final int ProgressWheel_text = 0;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#textColor}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:textColor
        */
        public static final int ProgressWheel_textColor = 1;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#textSize}
          attribute's value can be found in the {@link #ProgressWheel} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:textSize
        */
        public static final int ProgressWheel_textSize = 2;
        /**  PullToRefresh 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #PullToRefresh_ptrAdapterViewBackground com.ultrawise.softwareproduct.idevplatform:ptrAdapterViewBackground}</code></td><td> BELOW HERE ARE DEPRECEATED.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrAnimationStyle com.ultrawise.softwareproduct.idevplatform:ptrAnimationStyle}</code></td><td> Style of Animation should be used displayed when pulling.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrDrawable com.ultrawise.softwareproduct.idevplatform:ptrDrawable}</code></td><td> Drawable to use as Loading Indicator.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrDrawableBottom com.ultrawise.softwareproduct.idevplatform:ptrDrawableBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrDrawableEnd com.ultrawise.softwareproduct.idevplatform:ptrDrawableEnd}</code></td><td> Drawable to use as Loading Indicator in the Footer View.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrDrawableStart com.ultrawise.softwareproduct.idevplatform:ptrDrawableStart}</code></td><td> Drawable to use as Loading Indicator in the Header View.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrDrawableTop com.ultrawise.softwareproduct.idevplatform:ptrDrawableTop}</code></td><td></td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrHeaderBackground com.ultrawise.softwareproduct.idevplatform:ptrHeaderBackground}</code></td><td> A drawable to use as the background of the Header and Footer Loading Views </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrHeaderSubTextColor com.ultrawise.softwareproduct.idevplatform:ptrHeaderSubTextColor}</code></td><td> Text Color of the Header and Footer Loading Views Sub Header </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrHeaderTextAppearance com.ultrawise.softwareproduct.idevplatform:ptrHeaderTextAppearance}</code></td><td> Base text color, typeface, size, and style for Header and Footer Loading Views </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrHeaderTextColor com.ultrawise.softwareproduct.idevplatform:ptrHeaderTextColor}</code></td><td> Text Color of the Header and Footer Loading Views </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrListViewExtrasEnabled com.ultrawise.softwareproduct.idevplatform:ptrListViewExtrasEnabled}</code></td><td>
        	Whether PullToRefreshListView has it's extras enabled.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrMode com.ultrawise.softwareproduct.idevplatform:ptrMode}</code></td><td> Mode of Pull-to-Refresh that should be used </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrOverScroll com.ultrawise.softwareproduct.idevplatform:ptrOverScroll}</code></td><td> Whether Android's built-in Over Scroll should be utilised for Pull-to-Refresh.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrRefreshableViewBackground com.ultrawise.softwareproduct.idevplatform:ptrRefreshableViewBackground}</code></td><td> A drawable to use as the background of the Refreshable View </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrRotateDrawableWhilePulling com.ultrawise.softwareproduct.idevplatform:ptrRotateDrawableWhilePulling}</code></td><td>
        	Whether the Drawable should be continually rotated as you pull.</td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrScrollingWhileRefreshingEnabled com.ultrawise.softwareproduct.idevplatform:ptrScrollingWhileRefreshingEnabled}</code></td><td> Whether the user can scroll while the View is Refreshing </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrShowIndicator com.ultrawise.softwareproduct.idevplatform:ptrShowIndicator}</code></td><td> Whether the Indicator overlay(s) should be used </td></tr>
           <tr><td><code>{@link #PullToRefresh_ptrSubHeaderTextAppearance com.ultrawise.softwareproduct.idevplatform:ptrSubHeaderTextAppearance}</code></td><td> Base text color, typeface, size, and style for Header and Footer Loading Views Sub Header </td></tr>
           </table>
           @see #PullToRefresh_ptrAdapterViewBackground
           @see #PullToRefresh_ptrAnimationStyle
           @see #PullToRefresh_ptrDrawable
           @see #PullToRefresh_ptrDrawableBottom
           @see #PullToRefresh_ptrDrawableEnd
           @see #PullToRefresh_ptrDrawableStart
           @see #PullToRefresh_ptrDrawableTop
           @see #PullToRefresh_ptrHeaderBackground
           @see #PullToRefresh_ptrHeaderSubTextColor
           @see #PullToRefresh_ptrHeaderTextAppearance
           @see #PullToRefresh_ptrHeaderTextColor
           @see #PullToRefresh_ptrListViewExtrasEnabled
           @see #PullToRefresh_ptrMode
           @see #PullToRefresh_ptrOverScroll
           @see #PullToRefresh_ptrRefreshableViewBackground
           @see #PullToRefresh_ptrRotateDrawableWhilePulling
           @see #PullToRefresh_ptrScrollingWhileRefreshingEnabled
           @see #PullToRefresh_ptrShowIndicator
           @see #PullToRefresh_ptrSubHeaderTextAppearance
         */
        public static final int[] PullToRefresh = {
            0x7f010028, 0x7f010029, 0x7f01002a, 0x7f01002b,
            0x7f01002c, 0x7f01002d, 0x7f01002e, 0x7f01002f,
            0x7f010030, 0x7f010031, 0x7f010032, 0x7f010033,
            0x7f010034, 0x7f010035, 0x7f010036, 0x7f010037,
            0x7f010038, 0x7f010039, 0x7f01003a
        };
        /**
          <p>
          @attr description
           BELOW HERE ARE DEPRECEATED. DO NOT USE. 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrAdapterViewBackground
        */
        public static final int PullToRefresh_ptrAdapterViewBackground = 16;
        /**
          <p>
          @attr description
           Style of Animation should be used displayed when pulling. 


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>rotate</code></td><td>0x0</td><td></td></tr>
<tr><td><code>flip</code></td><td>0x1</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrAnimationStyle
        */
        public static final int PullToRefresh_ptrAnimationStyle = 12;
        /**
          <p>
          @attr description
           Drawable to use as Loading Indicator. Changes both Header and Footer. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrDrawable
        */
        public static final int PullToRefresh_ptrDrawable = 6;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#ptrDrawableBottom}
          attribute's value can be found in the {@link #PullToRefresh} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrDrawableBottom
        */
        public static final int PullToRefresh_ptrDrawableBottom = 18;
        /**
          <p>
          @attr description
           Drawable to use as Loading Indicator in the Footer View. Overrides value set in ptrDrawable. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrDrawableEnd
        */
        public static final int PullToRefresh_ptrDrawableEnd = 8;
        /**
          <p>
          @attr description
           Drawable to use as Loading Indicator in the Header View. Overrides value set in ptrDrawable. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrDrawableStart
        */
        public static final int PullToRefresh_ptrDrawableStart = 7;
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#ptrDrawableTop}
          attribute's value can be found in the {@link #PullToRefresh} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrDrawableTop
        */
        public static final int PullToRefresh_ptrDrawableTop = 17;
        /**
          <p>
          @attr description
           A drawable to use as the background of the Header and Footer Loading Views 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrHeaderBackground
        */
        public static final int PullToRefresh_ptrHeaderBackground = 1;
        /**
          <p>
          @attr description
           Text Color of the Header and Footer Loading Views Sub Header 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrHeaderSubTextColor
        */
        public static final int PullToRefresh_ptrHeaderSubTextColor = 3;
        /**
          <p>
          @attr description
           Base text color, typeface, size, and style for Header and Footer Loading Views 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrHeaderTextAppearance
        */
        public static final int PullToRefresh_ptrHeaderTextAppearance = 10;
        /**
          <p>
          @attr description
           Text Color of the Header and Footer Loading Views 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrHeaderTextColor
        */
        public static final int PullToRefresh_ptrHeaderTextColor = 2;
        /**
          <p>
          @attr description
          
        	Whether PullToRefreshListView has it's extras enabled. This allows the user to be 
        	able to scroll while refreshing, and behaves better. It acheives this by adding
        	Header and/or Footer Views to the ListView.
        


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrListViewExtrasEnabled
        */
        public static final int PullToRefresh_ptrListViewExtrasEnabled = 14;
        /**
          <p>
          @attr description
           Mode of Pull-to-Refresh that should be used 


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>disabled</code></td><td>0x0</td><td></td></tr>
<tr><td><code>pullFromStart</code></td><td>0x1</td><td></td></tr>
<tr><td><code>pullFromEnd</code></td><td>0x2</td><td></td></tr>
<tr><td><code>both</code></td><td>0x3</td><td></td></tr>
<tr><td><code>manualOnly</code></td><td>0x4</td><td></td></tr>
<tr><td><code>pullDownFromTop</code></td><td>0x1</td><td> These last two are depreacted </td></tr>
<tr><td><code>pullUpFromBottom</code></td><td>0x2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrMode
        */
        public static final int PullToRefresh_ptrMode = 4;
        /**
          <p>
          @attr description
           Whether Android's built-in Over Scroll should be utilised for Pull-to-Refresh. 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrOverScroll
        */
        public static final int PullToRefresh_ptrOverScroll = 9;
        /**
          <p>
          @attr description
           A drawable to use as the background of the Refreshable View 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrRefreshableViewBackground
        */
        public static final int PullToRefresh_ptrRefreshableViewBackground = 0;
        /**
          <p>
          @attr description
          
        	Whether the Drawable should be continually rotated as you pull. This only
        	takes effect when using the 'Rotate' Animation Style.
        


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrRotateDrawableWhilePulling
        */
        public static final int PullToRefresh_ptrRotateDrawableWhilePulling = 15;
        /**
          <p>
          @attr description
           Whether the user can scroll while the View is Refreshing 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrScrollingWhileRefreshingEnabled
        */
        public static final int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 13;
        /**
          <p>
          @attr description
           Whether the Indicator overlay(s) should be used 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrShowIndicator
        */
        public static final int PullToRefresh_ptrShowIndicator = 5;
        /**
          <p>
          @attr description
           Base text color, typeface, size, and style for Header and Footer Loading Views Sub Header 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.ultrawise.softwareproduct.idevplatform:ptrSubHeaderTextAppearance
        */
        public static final int PullToRefresh_ptrSubHeaderTextAppearance = 11;
        /** 
     Copyright (C) 2011 Patrik Åkerfeldt

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at
  
          http://www.apache.org/licenses/LICENSE-2.0
  
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ViewFlow_sidebuffer com.ultrawise.softwareproduct.idevplatform:sidebuffer}</code></td><td></td></tr>
           </table>
           @see #ViewFlow_sidebuffer
         */
        public static final int[] ViewFlow = {
            0x7f01000c
        };
        /**
          <p>This symbol is the offset where the {@link com.ultrawise.softwareproduct.idevplatform.R.attr#sidebuffer}
          attribute's value can be found in the {@link #ViewFlow} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.ultrawise.softwareproduct.idevplatform:sidebuffer
        */
        public static final int ViewFlow_sidebuffer = 0;
    };
}
